#echo -e "${color} Copy MongoDB Repo file ${nocolor}"
#cp /root/roboshop-shell/mongodb.repo /etc/yum.repos.d/mongodb.repo &>>$log_file
#
#
#echo -e "${color} Install MongoDB Client ${nocolor}"
#yum install mongodb-org-shell -y &>>$log_file
#
#
#echo -e "${color} Load Schema ${nocolor}"
#mongo --host mongodb-dev.harshadevops.shop <${app_path}/schema/$component.js &>>$log_file

- name: Copy MongoDB Repo file
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Install MongoDB Client
  ansible.builtin.yum:
    name:  mongodb-org-shell
    state: latest

- name: Load Schema
  ansible.builtin.shell: --host mongodb-dev.harshadevops.shop </app/schema/{{ component }}.js