# echo -e "${color} Setup systemd service  ${nocolor}"
# cp /root/roboshop-shell/$component.service /etc/systemd/system/$component.service &>>$log_file
# sed -i -e "s/roboshop_app_password/$roboshop_app_password/" /etc/systemd/system/$component.service 
# stat_chek $?
#
# echo -e "${color} Restart $component Service ${nocolor}"
# systemctl daemon-reload &>>$log_file
# systemctl enable $component  &>>$log_file
# systemctl restart $component &>>$log_file
# stat_chek $?

- name: Copy SystemD files
  ansible.builtin.copy:
      src: "{{ component }}.service"
      dest: /etc/systemd/system/{{ component }}.service

- name: Start {{ component }} Service   
  ansible.builtin.systemd:
      name: "{{ component }}" 
      state: restarted
      enabled: yes
      daemon-reload: yes  